services:
  - type: web
    name: ultimate-countdown
    env: python
    plan: free
    autoDeploy: true

    buildCommand: pip install -r requirements.txt

    # Flask via Gunicorn (recommand√© sur Render)
    startCommand: gunicorn app:app
